# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "^1.0.0"

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "^1.0.0"

[[constraint]]
  name = "cloud.google.com/go"
  version = "0.34.0"

[[override]]
  name = "gopkg.in/fsnotify.v1"
  source = "gopkg.in/fsnotify/fsnotify.v1"
