---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: jrjohnsongoog/stackdriver-tools-ci
inputs:
  - name: stackdriver-tools
  - name: stackdriver-tools-artifacts
  - name: stackdriver-tools-artifacts-sha1
  - name: stackdriver-nozzle-tile
outputs:
  - name: candidate

run:
  path: stackdriver-tools/ci/tasks/promote-candidate.sh
