---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: jrjohnsongoog/stackdriver-tools-ci
    tag: v3
inputs:
  - name: stackdriver-tools
run:
  path: stackdriver-tools/ci/tasks/public-semver.sh
params:
  # Google service account settings
  project_id:               replace me
  service_account_key_json: replace me
  bucket_name:              replace me
  semver_key:               replace me
