golang/go1.11.4.linux-amd64.tar.gz:
  size: 126643341
  object_id: 45bef95a-4ab8-46cb-43da-17acb22a64da
  sha: 52bd8eb353a39138a2ddf053857a0fd13f1f176c
google-fluentd-vendor/google-fluentd-vendor-0.14.25-plugin-0.6.15.tgz:
  size: 18673134
  object_id: cbae9e50-f009-441a-703a-2bcc0c561280
  sha: d16804bf8fed979d6d28a821b7bed54d701feb9e
libtool/libtool-2.4.2.tar.gz:
  size: 2632347
  object_id: a72448bd-9ae1-482a-54f3-a73f6820c2c4
  sha: 22b71a8b5ce3ad86e1094e7285981cae10e6ff88
libyajl/yajl-2.1.0.tar.gz:
  size: 84039
  object_id: 0a77c971-4860-4059-5bb7-8b3e0049f2ff
  sha: fe6b3c7439b26175aee59cabf8c4923b9eb3650d
python/Python-2.7.11.tgz:
  size: 16856409
  object_id: 5436eeb5-0322-4aff-5eac-a335d0ee2c72
  sha: 62a0b1b703d42999cc4aa9ee3c55eb7efe35802a
python/netifaces-0.10.4.tar.gz:
  size: 22969
  object_id: 7f3b60f2-f5ad-422e-708e-91d1e49be6f8
  sha: c3fcd491a89c2994815053e853b005e7fc27c79a
python/psutil-1.2.1.tar.gz:
  size: 167397
  object_id: 4e341411-e85b-453e-6a01-03b259700b57
  sha: c8c1842bf1c63b9068ac25a37f7aae11fcecd57f
python/setuptools-20.4.tar.gz:
  size: 675976
  object_id: ff2e938d-6ce7-4514-4d9f-a7197564f7af
  sha: b9ffbf5e29765c4a786c7242be1b03bfe08ad1c0
ruby/bundler-1.10.6.gem:
  size: 251392
  object_id: 810385aa-b9c4-4bb0-6f3b-446772507496
  sha: 55a37fccd1c0cb5542d468e35d3be46dd0667f73
ruby/ruby-2.3.0.tar.gz:
  size: 17648682
  object_id: 6b96ba17-ffbe-4d9a-7726-c695c1f4efc4
  sha: 2dfcf7f33bda4078efca30ae28cb89cd0e36ddc4
ruby/rubygems-2.6.2.tgz:
  size: 478660
  object_id: 90ddc55c-9119-42c7-5c8d-cc610dc5c6d8
  sha: 5960628b1f90f4a05ed69c0ad59c59cb10b79e5f
ruby/yaml-0.1.6.tar.gz:
  size: 503012
  object_id: fbd1083b-6f50-40d8-452a-d0c351326e40
  sha: f3d404e11bec3c4efcddfd14c42d46f1aabe0b5d
stackdriver-agent/stackdriver-agent_5.5.2-379.sdl.tgz:
  size: 1121897
  object_id: 7b4dfc20-9362-4cd5-4c2d-7e49f20a080f
  sha: 2dcca5209f6a708487f3d89e0db63fa914ef5230
